# Generated by Django 2.1.2 on 2018-11-26 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('language', models.CharField(choices=[('BANGLA', 'Bangla'), ('ENGLISH', 'English'), ('ARABIC', 'Arabic'), ('URDU', 'Urdu')], default='BANGLA', max_length=32)),
                ('category', models.CharField(choices=[('Spirituality', 'Spirituality'), ('Tafseer', 'Tafseer'), ('Hadith', 'Hadith'), ('Aqeedah', 'Aqeedah')], default='Spirituality', max_length=32)),
                ('publication', models.CharField(choices=[('None', 'None'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='None', max_length=32)),
                ('details', models.TextField()),
                ('mark', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='book1.jpeg', null=True, upload_to='%Y/%m/%d')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_model', to='bookmanagement.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('address', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BookTransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Refund', 'Refund'), ('Not Refund', 'Not Refund'), ('Pending', 'Pending')], default='Pending', max_length=32)),
                ('lend_from', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('message', models.TextField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.Book')),
                ('lend_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete='CASECADE', to='bookmanagement.Book')),
                ('commented_by', models.ForeignKey(on_delete='CASECADE', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete='CASECADE', related_name='replies', to='bookmanagement.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationFromBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.CharField(max_length=600)),
                ('creation_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to='bookmanagement.BookOwner'),
        ),
    ]
