# Generated by Django 2.1.2 on 2018-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransactionmodel',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
