# Generated by Django 2.1.2 on 2018-11-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181130_0604'),
        ('bookmanagement', '0004_auto_20181129_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(null=True, on_delete='CASECADE', to='blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='booktransactionmodel',
            name='status',
            field=models.CharField(choices=[('Not Refund', 'Not Refund'), ('Pending', 'Pending'), ('Refund', 'Refund')], default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(null=True, on_delete='CASECADE', to='bookmanagement.Book'),
        ),
    ]
