# Generated by Django 2.1.2 on 2018-11-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='title_content',
        ),
    ]
