# Generated by Django 2.1.2 on 2018-11-29 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_title_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='writter',
            field=models.ForeignKey(on_delete='CASECADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
